# Generated by Django 4.2.1 on 2024-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('on_or_off', models.TextField(max_length=2)),
                ('city', models.TextField(blank=True, max_length=255)),
                ('full_or_part', models.TextField(max_length=10)),
                ('salary', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('changed_time', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
