# Generated by Django 4.2.1 on 2024-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookForJob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
