# Generated by Django 4.2.1 on 2024-10-03 08:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lookForJob', '0002_job_company'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
