# Generated by Django 4.2.1 on 2024-10-03 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookForJob', '0003_alter_job_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
    ]
