# Generated by Django 4.2.1 on 2024-10-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('surname', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
                ('university', models.TextField(max_length=255)),
                ('specialization', models.TextField(max_length=255)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'ordering': ['time_create'],
            },
        ),
    ]
