# Generated by Django 4.2.1 on 2024-10-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookForStudent', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
