# Generated by Django 4.2.1 on 2024-10-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookForStudent', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
