# Generated by Django 4.2.1 on 2024-10-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookForStudent', '0009_specializationcategory_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookForStudent.specializationcategory'),
        ),
    ]
