# Generated by Django 4.2.1 on 2024-10-05 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookForStudent', '0010_alter_student_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='lookForStudent.specializationcategory'),
        ),
        migrations.AddField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='lookForStudent.tagstudent'),
        ),
    ]
